Add auth redirect component
CopenhagenCityArchives/linklives-frontend pull request #184
Opened 2021-08-16 14:27 UTC by HelenaBach

**toggl**: Gør det muligt at logge ind fra link rating siden  

### additions:

- login-completed component. this will handle 

### Changes:

- when you hit the login button, the linkKey and ratingoption is stored as url query params.

### TODO:
- refactor: reuse same login method everywhere in the application

2021-08-17 08:27 UTC, hypesystem requested changes
Reviewed the code for now - the interaction pattern seems good, but I will test it in the browser later, too.

2021-08-17 08:27 UTC, hypesystem commented on src/app/auth/auth0.component.ts
> +    }
Jeg tror jeg ville synes det var pænere hvis vi gemte det i ét JSON-objekt, med localstorage key "onLoginCompleted" eller noget (for at kommunikere at det er en instruktion til når login er done):

```js
{
  redirectTo: path, // denne kan også indeholde path
}
```

2021-08-17 08:27 UTC, hypesystem commented on src/app/auth/auth0.component.ts
> +    }
(Det skal JSON.stringify'es før det gemmes i localStorage, og JSON.parse's når det er hevet ud, men vi har færre writes til localstorage.)

2021-08-17 08:27 UTC, hypesystem commented on src/app/auth/login-completed/component.ts
> +    queryParams = JSON.parse('{"' + queryString.replace(/&/g, '","').replace(/=/g,'":"') + '"}', function(key, value) { return key===""?value:decodeURIComponent(value) })
Ikke stor fan af denne her regex til at lave query params til et objekt. Har vi ikke en helper funtion der gør det et andet sted?

Den er meget kompleks og der er mange måder den kan breake på på én linje, så den er super svær at debugge. Og derudover tror jeg ikke at den er komplet, ifht nogle fejl der ikke er fejl i browseren. F.eks. to  & efter hinanden, som vist er lovligt i browseren, men vil give et invalid objekt her, eller keys uden values (e.g. `?hello&world`) som er valid i browseren og ikke i JSON (`{"hello","world"}`).

2021-08-17 08:27 UTC, hypesystem commented on src/app/life-course/life-course.component.ts
> +      console.log('next.lifecourse.chosenRatingId', next.lifecourse.chosenRatingId);
Comment should probably be removed

2021-08-17 08:27 UTC, hypesystem commented on src/app/life-course/life-course.component.ts
> +    console.log('cosen', chosenRatingId);
Comment should probably be removed

2021-08-17 08:27 UTC, hypesystem commented on src/app/link-rating/component.ts
> +
Space characters floating here

2021-08-17 08:27 UTC, hypesystem commented on src/app/link-rating/component.ts
> +    this.router.navigate([window.location.pathname], { // reset url query
I would move comment to over the call, or extract the call to a function called `resetUrlQuery`. But more than that, I feel like it "clears" (rather than "resets", implying some other state that may or may not be empty) the query.

2021-08-17 08:27 UTC, hypesystem commented on src/app/life-course/life-course-resolver.service.ts
> +    const chosenRatingId = route.queryParamMap.get('chosenRatingId') || '';
I don't see any reason to do this in the resolver. In many other places we just do it in ngOnInit in the component.

2021-08-17 08:27 UTC, hypesystem commented on src/app/link-rating/component.ts
> +      })
All this code setting localStorage items with state that we want to use on login completed, and doing the actual redirect, is a prime candidate for extraction to some util function. We use it in two places, and it is already hard to me to get a grasp of how I would maintain it so it stays in sync.

2021-08-17 10:17 UTC, HelenaBach commented on src/app/auth/login-completed/component.ts
> +    queryParams = JSON.parse('{"' + queryString.replace(/&/g, '","').replace(/=/g,'":"') + '"}', function(key, value) { return key===""?value:decodeURIComponent(value) })
Nej det er jeg virkelig heller ikke, håbede at du måske havde en bedre løsning eller et bibliotek gemt et eller andet sted? :)

2021-08-17 10:23 UTC, HelenaBach commented on src/app/link-rating/component.ts
> +      })
I very much agree, this is actually why I set the LinkKey and chosenRatingId as query params, so that the rest of the code could easily be extracted.

2021-08-18 10:15 UTC, merged

2021-08-20 06:51 UTC, hypesystem reviewed
Had some comments, mostly minor, and a single case for error handling.

2021-08-20 06:51 UTC, hypesystem commented on src/app/auth/login-completed/component.ts
> +import { URIQueryToObj } from '../../util/util';
Don't mix cases + avoid uncommon abbreviations + functions start with lowercase: should be `uriQueryToObject`.

A name more focused on the action it performs (indicating that it is a function) could be `getObjectFromQueryString`

2021-08-20 06:51 UTC, hypesystem commented on src/app/util/util.js
> +    }
Instead of writing `result[cleanedKey]` several times, this could be an if-return (early out)

2021-08-20 06:51 UTC, hypesystem commented on angular.json
> +}
Missing newline @ eof

2021-08-20 06:51 UTC, hypesystem commented on src/app/auth/auth-button/component.html
> +</ng-template>
Missing newline @ eof

2021-08-20 06:51 UTC, hypesystem commented on src/app/auth/auth-button/component.ts
> +      onLoginCompleted['query'] = window.location.search.substring(1);
Prettier (no need to use the [] indexer syntax):

```js
onLoginCompleted.query = window.location.search.substring(1);
```

2021-08-20 06:51 UTC, hypesystem commented on src/app/auth/login-completed/component.ts
> +    const { path, query } = JSON.parse(stateString);
Would recommend try/catch around JSON.parse - failure to parse the data in the field should result in the same thing as if there was no data in there (e.g. navigate to /). Right now, invalid data means we crash and do nothing.

2021-08-20 06:51 UTC, hypesystem commented on src/app/link-rating/component.ts
> +        onLoginCompleted['query'] = window.location.search.substring(1);
Same note as above: `onLoginCompleted.query`

2021-08-20 06:51 UTC, hypesystem commented on src/app/auth/auth.service.js
> +}
This file seems empty and unused? Should remove?