Lifecourse view layout
CopenhagenCityArchives/linklives-frontend pull request #21
Opened 2020-11-16 14:44 UTC by Arth101

2020-11-17 19:41 UTC, hypesystem requested changes
Reviewed :smile:

Generally the code looks really nice, but I think we should align the source view and life course view headers and footers, as they are designed identically in Sketch :smile:

Måske værd at reviewe og merge #22 først, fordi den opdaterer footeren.

2020-11-17 19:41 UTC, hypesystem commented on src/assets/styling/utility.scss
> +}
Missing newline @ eof

2020-11-17 19:41 UTC, hypesystem commented on src/assets/styling/utility.scss
> +  margin-right: 10px !important;
I think we should define these using rem? `0.625rem` in this case.

2020-11-17 19:41 UTC, hypesystem commented on src/assets/styling/lifecourse-page.scss
> +}
Missing newline @ eof

2020-11-17 19:41 UTC, hypesystem commented on src/assets/styling/lifecourse-page.scss
> +
odd newline here i think?

2020-11-17 19:41 UTC, hypesystem commented on src/app/search-result-list/search-result-list.component.html
>  </div>
missing newline @ eof

2020-11-17 19:41 UTC, hypesystem commented on src/app/life-course/life-course.component.html
>  </div>
Missing newline @ eof

2020-11-17 19:41 UTC, hypesystem commented on src/app/life-course/life-course.component.html
> +    </section>
I think for this entire header you should have extracted and reused the one from the source view?

![image](https://user-images.githubusercontent.com/859106/99439038-f4ea1b80-2914-11eb-98eb-ac1de509b3f2.png)

2020-11-17 19:41 UTC, hypesystem commented on src/app/life-course/life-course.component.html
> +            <p>{{ lifecourseId }}</p>
The first part of the ID here could have been based on the one in the source view, too, including the href :smile:

2020-11-17 19:41 UTC, hypesystem commented on src/app/life-course/life-course.component.html
> +    </section>
Maybe not extracting the content, but at least the styling?

2020-11-17 19:41 UTC, hypesystem commented on src/app/life-course/life-course.component.html
> +                <a class="lls-btn" href="">Download</a>
Signe told us at the start that we shouldn't have the download buttons in this iteration

2020-11-18 11:22 UTC, Arth101 commented on src/app/life-course/life-course.component.html
> +                <a class="lls-btn" href="">Download</a>
I'll remove them :)

2020-11-18 11:23 UTC, Arth101 commented on src/app/life-course/life-course.component.html
> +    </section>
Makes sense. It is extracted to `data-page-header`.

2020-11-18 11:30 UTC, Arth101 commented on src/app/life-course/life-course.component.html
> +            <p>{{ lifecourseId }}</p>
This ID seems to be just "1" all the time. I've made a TODO comment but I think we should fix it later and get this merged.

2020-11-18 12:40 UTC, hypesystem approved these changes

2020-11-18 13:39 UTC, merged