Update source graph tooltip
CopenhagenCityArchives/linklives-frontend pull request #228
Opened 2021-11-03 14:59 UTC by Arth101

Trello: https://trello.com/c/L6ngCzVG/238-nyt-design-og-tekst-p%C3%A5-bl%C3%A5-link-boks

Toggl: `Nyt design og tekst på blå link boks`

### Changes:
- Change text and tweak markup in source-graph-link tooltip.
- Set "totalRatings" variable when a link is hovered, since we need to show the number of ratings in the tooltip. 

### Screenshot
![Screenshot from 2021-11-03 15-56-37](https://user-images.githubusercontent.com/8166831/140084840-f059b4f4-b744-4389-8c61-1363ed9c921a.png)

2021-11-08 10:48 UTC, hypesystem requested changes
Requesting padding in blue box to fit with design in Sketch:

![image](https://user-images.githubusercontent.com/859106/140729031-e53998e7-9163-45a7-961f-59467527afb2.png)

2021-11-08 10:48 UTC, hypesystem commented on src/app/life-course/source-linking-graph.component.ts
> +    });
Jeg ville hellere loade alle ratings on init og bare vise dem når vi hover - så slipper vi for at der sker updates af tallet efter man bevæger musen ind over.

2021-11-08 10:48 UTC, hypesystem commented on src/app/life-course/source-linking-graph.component.ts
> +    });
I virkeligheden ville jeg nok gøre det ude i life-course siden, og passe data'en ind i denne component, i stedet for at denne component afhænger af elasticsearch service, ogås.

2021-11-12 14:20 UTC, Arth101 commented on src/app/life-course/source-linking-graph.component.ts
> +    });
Jeg fandt ud af at rating data allerede var i `this.link`, så det valgte jeg bare at bruge. Det er ret clean og krævede ikke nogle udregninger eller ekstra data.

2021-11-19 11:06 UTC, hypesystem commented on src/app/life-course/source-linking-graph.component.ts
> +    });
:+1:

2021-11-19 11:11 UTC, hypesystem requested changes
Two small comments/change requests

2021-11-19 11:11 UTC, hypesystem commented on src/assets/styling/source-graph.scss
> -  height: 245px;
Why remove the height?

The tooltips are positioned by `top` so this might result in misalignment between the pointy tip :after-element and the node on the link path

2021-11-19 11:11 UTC, hypesystem commented on src/app/life-course/source-linking-graph.component.ts
> +  constructor(private elasticsearch: ElasticsearchService) { }
This can be removed now as it is no longer used :smile:

2021-11-19 11:14 UTC, Arth101 commented on src/assets/styling/source-graph.scss
> -  height: 245px;
Højden er lidt random, men jeg mente at det var bedre at man altid kan se alt content i boksen, end at den altid er aligned med pointy-tip. Lige nu passer den "naturlige" højde som elementet har med pointy-tip alignement.

2021-11-22 12:37 UTC, hypesystem approved these changes

2021-11-22 12:47 UTC, merged